# Generated by Django 2.2 on 2020-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=50, null=True, verbose_name='课程名'),
        ),
    ]
