# Generated by Django 2.2 on 2020-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200914_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, null=True, verbose_name='公司职位'),
        ),
    ]
